chain_id: 1001
program_id: "CmobH2vR6aUtQ8x4xd1LYNiH6k2G7PFT5StTgWqvy2VU"
start_slot: 0
solana:
  rpc_url: "http://solana:8899"
  commitment: "confirmed"
payers:
  - payer_keypair: "/opt/proxy-sender.json"
    number_holders: 4
  - payer_keypair: "/opt/proxy-sender-2.json"
    number_holders: 16
  - payer_keypair: "/opt/proxy-sender-3.json"
    number_holders: 64
proxy_host: "0.0.0.0:9090"
max_slot_history: 4096
